### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by retronbv** [SharpScratchMod/SharpScratchMod.github.io#6]
Is this project still going?
If it is you might want to move away from Adobe Flash because it is “depreciated”

**Comment by Mrcomputer1** [comment]
I do want to upgrade Sharp to be Scratch 3.0-based at some point. As for the current 2.0-based version of Sharp, I would say that it is discontinued due to Flash being EOL.

Although Flash Player might no longer work in browsers, it is still possible to use Sharp by downloading [Sharp.swf](https://sharpscratchmod.github.io/Sharp.swf) and using the [Flash Player projector](https://www.adobe.com/support/flashplayer/debug_downloads.html). Surprisingly the Flash Player projector can still be downloaded from Adobe's website, even though basically every other Flash Player download has been removed from their website.
